name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Test
        uses: willcaul/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'npm run coverage-jenkins'

      - name: Save Code Linting Report JSON
        run: npm run lint:json
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: './coverage/'

      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: ./coverage/
